version: '3.3'

services:
  strapi:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 1337:1337
      - 2000:22

    healthcheck:
      test: curl --fail http://localhost:1337 || exit 1
      interval: 60s
      retries: 10
      start_period: 20s
      timeout: 10s

  front:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - HOST=strapi
    ports:
      - 3000:3000
      - 24678:24678
    depends_on:
      strapi:
        condition: service_healthy
